version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    ## here db_data is the host volume which must be same as in the volumes at the end of the file
    - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.6.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      ## set to "false" to disable console
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      ## HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  web:
    ## if the image is hosted on aws ecr then add the ecr repo url or if the image is in docker hub then also add the image link with image: [url]
    build: ./app
    command: npm run dev
    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
volumes:
  db_data:
